<?php
/**
 * @var $this IWD_Opc_Block_Onepage_Wrapper
 * @var $opcHelper IWD_Opc_Helper_Data
 */
?>
<?php
$opcHelper = $this->getOpcHelper();
$showLoginButton = !$this->isCustomerLoggedIn() && $opcHelper->isShowLoginButton();
?>
<div class="iwd_opc_clear"></div>
<div class="iwd_opc_wrapper">
    <div class="iwd_opc_alternative_wrapper
            <?php /*if ($this->isVirtual()) { ?>
            iwd_opc_two_column_wrapper
            <?php }*/ ?>
    ">
        <script type="text/javascript">
            var iwdOpcConfig = '<?php echo $this->jsQuoteEscape($this->getJsonConfig()); ?>';
            Validation.defaultOptions.addClassNameToContainer = true;
            Validation.defaultOptions.containerClassName = '.iwd_opc_universal_wrapper';
        </script>
        <?php if ($showLoginButton) { ?>
            <div class="iwd_opc_top">
                <div class="iwd_opc_top_buttons" data-has-login="true">
                    <?php echo $this->getChildHtml('paypal_express'); ?>
                    <?php echo $this->getChildHtml('paypaluk_express'); ?>
                </div>
            </div>
        <?php } ?>
        <div class="iwd_opc_top">
            <?php if ($showLoginButton) { ?>
                <div class="iwd_opc_top_buttons">
                    <button type="button"
                            id="iwd_opc_top_login_button"
                            class="iwd_opc_button active"
                            title="<?php echo $this->escapeHtml($this->__('Login')) ?>">
                        <?php echo $this->escapeHtml($this->__('Login')) ?>
                    </button>
                </div>
            <?php } else { ?>
                <div class="iwd_opc_top_buttons" data-has-login="false">
                    <?php echo $this->getChildHtml('paypal_express'); ?>
                    <?php echo $this->getChildHtml('paypaluk_express'); ?>
                </div>
            <?php } ?>
            <div id="iwd_opc_top_review" tabindex="-1">
                <?php echo $this->getChildHtml('review'); ?>
            </div>
        </div>
        <div class="iwd_opc_clear"></div>
        <div class="iwd_opc_column" id="iwd_opc_address_column">
            <div class="iwd_opc_alternative_column">
                <div class="iwd_opc_universal_wrapper iwd_opc_column_status">
                    <div class="iwd_opc_column_alternative_status">
                        1
                    </div>
                </div>
                <div class="iwd_opc_column_content" tabindex="-1">
                    <div id="iwd_opc_billing_address">
                        <form class="iwd_opc_form" id="iwd_opc_billing_form">
                            <?php if (!$this->isCustomerLoggedIn()) { ?>
                                <div id="iwd_opc_login">
                                    <?php echo $this->getChildHtml('login'); ?>
                                    <?php echo $this->getChildHtml('loader'); ?>
                                </div>
                                <div class="iwd_opc_section_delimiter"></div>
                            <?php } ?>
                            <div class="iwd_opc_universal_wrapper iwd_opc_message iwd_opc_section_message error_message"
                                 style="display:none;">

                            </div>
                            <?php echo $this->getChildHtml('billing_address'); ?>
                        </form>
                        <?php echo $this->getChildHtml('loader'); ?>
                    </div>
                    <script type="text/javascript">
                        var iwdOpcBillingAddressForm = new VarienForm('iwd_opc_billing_form');
                        iwdOpcBillingAddressForm.validator.options = {
                            onSubmit: false,
                            stopOnFirst: false,
                            immediate: false,
                            focusOnError: false,
                            useTitles: false,
                            onFormValidate: function (result, form) {
                            },
                            onElementValidate: function (result, elm) {
                            }
                        };
                    </script>
                    <?php if (!$this->isVirtual()) {
                        ?>
                        <div id="iwd_opc_shipping_address"
                            <?php if (!$this->isShowShippingForm()) { ?>
                                style="display:none;"
                            <?php } ?>
                        >
                            <div class="iwd_opc_universal_wrapper iwd_opc_message iwd_opc_section_message error_message"
                                 style="display:none;">

                            </div>
                            <form class="iwd_opc_form" id="iwd_opc_shipping_form">
                                <?php echo $this->getChildHtml('shipping_address'); ?>
                            </form>
                            <?php echo $this->getChildHtml('loader'); ?>
                        </div>
                        <script type="text/javascript">
                            var iwdOpcShippingAddressForm = new VarienForm('iwd_opc_shipping_form');
                            iwdOpcShippingAddressForm.validator.options = {
                                onSubmit: false,
                                stopOnFirst: false,
                                immediate: false,
                                focusOnError: false,
                                useTitles: false,
                                onFormValidate: function (result, form) {
                                },
                                onElementValidate: function (result, elm) {
                                }
                            };
                        </script>
                    <?php }
                    /*else { ?>
                    <?php if ($opcHelper->isShowCommentField()) { ?>
                        <div class="iwd_opc_section_delimiter"></div>
                        <div id="iwd_opc_comment">
                            <?php echo $this->getChildHtml('comment'); ?>
                            <?php echo $this->getChildHtml('loader'); ?>
                        </div>
                    <?php } ?>
                    <?php } */ ?>
                </div>
            </div>
        </div>
        <!--        --><?php //if (!$this->isVirtual()) { ?>
        <div class="iwd_opc_column" id="iwd_opc_shipping_column">
            <div class="iwd_opc_alternative_column">
                <div class="iwd_opc_universal_wrapper iwd_opc_column_status">
                    <div class="iwd_opc_column_alternative_status">
                        2
                    </div>
                </div>
                <div class="iwd_opc_column_content" tabindex="-1">
                    <div id="iwd_opc_shipping_method">
                        <div class="iwd_opc_universal_wrapper iwd_opc_message iwd_opc_section_message error_message"
                             style="display:none;">

                        </div>
                        <?php echo $this->getChildHtml('shipping_method'); ?>
                        <?php if (!$this->isVirtual()) { ?>
                            <?php echo $this->getChildHtml('loader'); ?>
                        <?php } ?>
                    </div>
                    <?php if ($opcHelper->isShowCommentField()
                        || ($opcHelper->isShowGiftMessage() && !$this->isVirtual())
                    ) { ?>
                        <div class="iwd_opc_section_delimiter"></div>
                    <?php } ?>
                    <?php if ($opcHelper->isShowCommentField()) { ?>
                        <div id="iwd_opc_comment">
                            <?php echo $this->getChildHtml('comment'); ?>
                            <?php echo $this->getChildHtml('loader'); ?>
                        </div>
                    <?php } ?>
                    <?php if ($opcHelper->isShowGiftMessage() && !$this->isVirtual()) { ?>
                        <div id="iwd_opc_gift_message">
                            <div class="iwd_opc_universal_wrapper iwd_opc_message
                                iwd_opc_section_message error_message"
                                 style="display:none;">

                            </div>
                            <?php echo $this->getChildHtml('gift_message'); ?>
                            <?php echo $this->getChildHtml('loader'); ?>
                        </div>
                    <?php } ?>
                </div>
            </div>
        </div>
        <!--        --><?php //} ?>
        <div class="iwd_opc_column" id="iwd_opc_payment_column">
            <div class="iwd_opc_alternative_column">
                <div class="iwd_opc_universal_wrapper iwd_opc_column_status">
                    <div class="iwd_opc_column_alternative_status">
                        <!--                        --><?php //if ($this->isVirtual()) { ?>
                        <!--                            2-->
                        <!--                        --><?php //} else { ?>
                        3
                        <!--                        --><?php //} ?>
                    </div>
                </div>
                <div class="iwd_opc_column_content" tabindex="-1">
                    <div id="iwd_opc_payment">
                        <?php echo $this->getChildHtml('payment'); ?>
                        <?php echo $this->getChildHtml('loader'); ?>
                    </div>
                    <?php if ($opcHelper->isShowSubscribe()) { ?>
                        <div id="iwd_opc_subscribe">
                            <?php echo $this->getChildHtml('subscribe'); ?>
                        </div>
                        <div class="iwd_opc_section_delimiter"></div>
                    <?php } ?>
                    <?php echo $this->getChildHtml('agreements'); ?>
                    <div id="iwd_opc_place_order">
                        <div class="iwd_opc_universal_wrapper">
                            <button type="button"
                                    id="iwd_opc_place_order_button"
                                    title="<?php echo $this->escapeHtml($this->__('Place Order')); ?>"
                                    class="iwd_opc_button active">
                                <?php echo $this->escapeHtml($this->__('Place Order')); ?>
                            </button>
                        </div>
                        <div class="iwd_opc_universal_wrapper iwd_opc_message info_message" style="display:none;">
                            <?php echo $this->escapeHtml($this->__('All required fields haven\'t been filled.')) ?>
                        </div>
                    </div>
                    <div class="iwd_opc_universal_wrapper">

                    </div>
                </div>
            </div>
        </div>
        <div class="iwd_opc_clear"></div>
        <?php echo $this->getChildHtml('loader'); ?>
    </div>
</div>
<div class="iwd_opc_clear"></div>
