<?php

  // Get logged in customer
  $customer = Mage::getSingleton('customer/session')->getCustomer();
  $email = $customer->getEmail();

  $_product = Mage::getModel('catalog/product')->load($this->getBusinessDetails());

?>
<div class="customerasaproduct-container">
  <form id="business-register" enctype="multipart/form-data" onsubmit="<?php if ($this->getBusinessDetails() == '') { echo 'return(validateCover());'; } else { echo ''; } ?>" method="post" action="<?php if ($this->getBusinessDetails() != '') { echo Mage::getUrl('customerasaproduct/index/update'); } else { echo Mage::getUrl('customerasaproduct/index/post'); } ?>">
    <fieldset class="group-select">
      <h3 class="legend"><?php echo $this->__("Design your business page"); ?></h3>
      <h4 class="legend"><?php echo $this->__("Basic details"); ?></h4>
      <ul>
        <li>
          <input name="product-id" style="display: none" value="<?php echo $_product->getId() ?>" class="" />
          <div class="input-box">
            <label for="name"><?php echo $this->__("Name"); ?></label><br />
            <input name="name" id="name" title="Name" value="<?php echo $_product->getName() ?>" class="required-entry input-text" maxlength="30" type="text" />
          </div>
          <div class="input-box">
            <label for="category"><?php echo $this->__("Category"); ?></label><br />
            <?php
              $category = Mage::getModel('catalog/category');
              if(is_object(Mage::registry('current_category'))){
                $current_category_path=Mage::registry('current_category')->getPathIds();
              }else{
                $current_category_path = array();
              }
              $category->load(Mage::app()->getStore()->getRootCategoryId());
              $children_string = $category->getChildren();
              $children = explode(',',$children_string);
              $extra_options='';

              foreach($children as $c){
                $selected = (in_array($c, $current_category_path))?'SELECTED':'';
                $extra_options.= '<option value="' . $c . '" ' . $selected . '>' . $category->load($c)->getName() . '</option>' . "\n";
              }
            ?>
            <select name="category" id="cat" class="required-entry input-text">
              <?php $selected_category = $_product->getCategoryIds() ?>
              <?php $selected_category_name = Mage::getModel('catalog/category')->load($selected_category)->getName() ?>
               <option value="<?php echo $selected_category[0] . " SELECTED"?> "><?php echo $selected_category_name ?></option>
               <?php echo $extra_options ?>
            </select>
          </div>
          <div class="input-box">
            <label for="cover-image"><?php echo $this->__("Cover Image"); ?></label><br />
            <input name="cover-image" id="cover-image" onchange="return imageValidation()" title="Cover Image" value="" class="<?php if ($this->getBusinessDetails() == '') { echo 'required-entry'; } else { echo ''; } ?>" type="file" />
            <p class="cover-image-validation" style="display: none; color: red; text-align: left; margin-top: 10px;"><?php echo $this->__("Please attach a cover image.") ?></p>
          </div>
          <div class="input-box">
            <label for="telephone-1"><?php echo $this->__("Telephone 1"); ?></label><br />
            <input name="telephone" id="telephone-1" title="Telephone 1" value="<?php echo $_product->getPhone(); ?>" class="required-entry input-text" type="text" maxlength="20" />
          </div>
          <div class="input-box">
            <label for="telephone"><?php echo $this->__("Telephone 2"); ?></label><br />
            <input name="telephone-2" id="telephone-2" title="Telephone 2" value="<?php echo $_product->getPhone2(); ?>" class="input-text" type="text" maxlength="20" />
          </div>
          <div class="input-box">
            <label for="email"><?php echo $this->__("Email"); ?></label><br />
            <input style="display: none" name="email" id="email" title="Email" value="<?php echo $email ?>" class="input-text required-entry validate-email" type="text" maxlength="20" />
            <p style="text-align: left;"><?php echo $email ?></p>
          </div>
          <div class="input-box">
            <label for="City"><?php echo $this->__("City"); ?></label><br />
            <?php
              $atributeCode = 'city';
              $attribute = Mage::getModel('eav/config')->getAttribute('catalog_product',$atributeCode);
              $options = $attribute->getSource()->getAllOptions();
            ?>
            <select name="city" id="city" class="required-entry input-text">
              <option value="<?php echo $_product->getCityAttr() ?>" selected="selected" ><?php echo $_product->getCityAttr() ?></option>
              <?php foreach($options as $key => $value): ?>
                <option value="<?php echo $value['label']; ?>" <?php if($key == $result['city'] && $key != ''): ?> selected="selected" <?php endif; ?> ><?php echo $value['label']; ?></option>
              <?php endforeach; ?>
            </select>
          </div>
          <div class="input-box address-map">
            <label for="Address"><?php echo $this->__("Address"); ?></label><br />
            <input name="address" id="address" title="Address" value="<?php echo $_product->getAddress(); ?>" class="required-entry input-text" maxlength="50" type="text" />
            <input id="map-submit" type="button" class="button button-submit-map" value="<?php echo $this->__("Mark map"); ?>" />
            <input onclick="clearOverlays();" type=button class="button button-submit-map" value="<?php echo $this->__("Delete markers"); ?>" />
            <p><small style="float: left;"><?php echo $this->__("* Street format: [Street] [Street Number], [City]"); ?></small></p>
            <h4 class="legend"><?php echo $this->__("Map"); ?></h4>
            <div class="customerasaproduct-map" id="customerasaproduct-map" style="width: 500px; height: 300px"></div>
            <input type="hidden" id="map-input-lat" name="map-lat" />
            <input type="hidden" id="map-input-lng" name="map-lng" />
          </div>
          <div class="clear"></div>
          <h4 class="legend"><?php echo $this->__("Links"); ?></h4>
          <div class="input-box">
            <label for="webpage"><?php echo $this->__("Web Page"); ?></label><br />
            <input name="webpage" id="webpage" title="webpage" value="<?php echo $_product->getWebpage(); ?>" class="input-text validate-url" type="text" maxlength="100" />
          </div>
          <div class="input-box">
            <label for="facebook"><?php echo $this->__("Facebook"); ?></label><br />
            <input name="facebook" id="facebook" title="facebook" value="<?php echo $_product->getFacebook(); ?>" class="input-text validate-url" type="text" maxlength="100" />
          </div>
          <div class="input-box">
            <label for="twitter"><?php echo $this->__("Twitter"); ?></label><br />
            <input name="twitter" id="twitter" title="twitter" value="<?php echo $_product->getTwitter(); ?>" class="input-text validate-url" type="text" maxlength="100" />
          </div>
          <div class="input-box">
            <label for="instagram"><?php echo $this->__("Instagram"); ?></label><br />
            <input name="instagram" id="instagram" title="instagram" value="<?php echo $_product->getInstagram(); ?>" class="input-text validate-url" type="text" maxlength="100" />
          </div>
        </li>
      </ul>
      <div class="input-box">

      </div>
      <div class="customerasaproduct-container1">
        <h4 class="legend"><?php echo $this->__("Working hours"); ?></h4>
        <ul>
          <li>
            <div class="input-box">
              <div class="working-hours">
                <label for="monday"><?php echo $this->__("Monday"); ?></label><br />
                <input name="monday-from" id="monday" title="monday" value="<?php echo $_product->getMonday(); ?>" class="required-entry input-text validate-hours" type="text" maxlength="5" />
                <input name="monday-to" id="monday" title="monday" value="<?php echo $_product->getMondayTo(); ?>" class="required-entry input-text validate-hours" type="text" maxlength="5" />
              </div>
            </div>
          </li>
          <li>
            <div class="input-box">
              <div class="working-hours">
                <label for="tuesday"><?php echo $this->__("Tuesday"); ?></label><br />
                <input name="tuesday-from" id="tuesday" title="tuesday" value="<?php echo $_product->getTuesday(); ?>" class="required-entry input-text validate-hours" type="text" maxlength="25" />
                <input name="tuesday-to" id="tuesday" title="tuesday" value="<?php echo $_product->getTuesdayTo(); ?>" class="required-entry input-text validate-hours" type="text" maxlength="25" />
              </div>
            </div>
          </li>
          <li>
            <div class="input-box">
              <div class="working-hours">
                <label for="wednesday"><?php echo $this->__("Wednesday"); ?></label><br />
                <input name="wednesday-from" id="wednesday" title="wednesday" value="<?php echo $_product->getWednesday(); ?>" class="required-entry input-text validate-hours" type="text" maxlength="25" />
                <input name="wednesday-to" id="wednesday" title="wednesday" value="<?php echo $_product->getWednesdayTo(); ?>" class="required-entry input-text validate-hours" type="text" maxlength="25" />
              </div>
            </div>
          </li>
          <li>
            <div class="input-box">
              <div class="working-hours">
                <label for="thursday"><?php echo $this->__("Thursday"); ?></label><br />
                <input name="thursday-from" id="thursday" title="thursday" value="<?php echo $_product->getThursday(); ?>" class="required-entry input-text validate-hours" type="text" maxlength="25" />
                <input name="thursday-to" id="thursday" title="thursday" value="<?php echo $_product->getThursdayTo(); ?>" class="required-entry input-text validate-hours" type="text" maxlength="25" />
              </div>
            </div>
          </li>
          <li>
            <div class="input-box">
              <div class="working-hours">
                <label for="friday"><?php echo $this->__("Friday"); ?></label><br />
                <input name="friday-from" id="friday" title="friday" value="<?php echo $_product->getFriday(); ?>" class="required-entry input-text validate-hours" type="text" maxlength="25" />
                <input name="friday-to" id="friday" title="friday" value="<?php echo $_product->getFridayTo(); ?>" class="required-entry input-text validate-hours" type="text" maxlength="25" />
              </div>
            </div>
          </li>
          <li>
            <div class="input-box">
              <fieldset id="sunday-radio">
                <label for="saturday"><?php echo $this->__("Saturday"); ?></label>
                <label><?php echo $this->__("day in"); ?></label>
                <input type="radio" name="saturday-radio" id="saturday-radio-enable" value="dayoff" >
                <label><?php echo $this->__("day off"); ?></label>
                <input type="radio" name="saturday-radio" id="saturday-radio-disable" value="dayin" >
              </fieldset>
              <div class="working-hours">
                <input name="saturday-from" id="saturday-from-input" title="sunday" value="<?php echo $_product->getSaturday(); ?>" class="input-text validate-hours" type="text" maxlength="25" />
                <input name="saturday-to" id="saturday-to-input" title="sunday" value="<?php echo $_product->getSaturdayTo(); ?>" class="input-text validate-hours" type="text" maxlength="25" />
              </div>
            </div>
          </li>
          <li>
            <div class="input-box">
              <fieldset id="sunday-radio">
                <label for="sunday"><?php echo $this->__("Sunday"); ?></label>
                <label><?php echo $this->__("day in"); ?></label>
                <input type="radio" name="sunday-radio" id="sunday-radio-enable" value="dayoff" >
                <label><?php echo $this->__("day off"); ?></label>
                <input type="radio" name="sunday-radio" id="sunday-radio-disable" value="dayin" >
              </fieldset>
              <div class="working-hours">
                <input name="sunday-from" id="sunday-from-input" title="sunday" value="<?php echo $_product->getSunday(); ?>" class="input-text" type="text" maxlength="25" />
                <input name="sunday-to" id="sunday-to-input" title="sunday" value="<?php echo $_product->getSundayTo(); ?>" class="input-text" type="text" maxlength="25" />
              </div>
            </div>
          </li>
        </ul>
      </div>
      <div class="customerasaproduct-container2">
        <label for="about-us" ><?php echo $this->__("About us"); ?></h4>
        <div class="input-box">
          <textarea name="about-us" id="about-us" title="about-us" value="" class="required-entry input-text" type="text" maxlength="500"><?php echo $_product->getShortDescription(); ?></textarea>
        </div>
      </div>

      <div class="customerasaproduct-container3">
        <label for="photogallery"><?php echo $this->__("Photogallery"); ?></label>
        <div class="input-box">
          <input name="media-image-1" id="media-image-1" title="Media Image" value="" class="" type="file" />
          <input name="media-image-2" id="media-image-2" title="Media Image" value="" class="" type="file" />
          <input name="media-image-3" id="media-image-3" title="Media Image" value="" class="" type="file" />
          <input name="media-image-4" id="media-image-4" title="Media Image" value="" class="" type="file" />
          <input name="media-image-5" id="media-image-5" title="Media Image" value="" class="" type="file" />
          <input name="media-image-6" id="media-image-6" title="Media Image" value="" class="" type="file" />
        </div>
      </div>

      <div class="customerasaproduct-container4">
        <label for="promotions" ><?php echo $this->__("Actions, sale, promotions"); ?></label>
        <div class="input-box">
          <textarea name="company-promotions" id="promotions" title="promotions" value="" class="input-text" type="text" maxlength="500"><?php echo $_product->getCompanyPromotions(); ?></textarea>
      </div>
      </div>

    </fieldset>
    <?php if ($this->getBusinessDetails() != ''): ?>
      <div class="buttons-set">
          <a class="button" href="<?php echo Mage::getUrl('customer/account'); ?>" type=""><span><?php echo $this->__("Cancel") ?></span></a>
          <button class="form-button-confirm button" type="submit"><span><?php echo $this->__("Update") ?></span></button>
      </div>
    <?php else: ?>
      <div class="buttons-set">
          <a class="button" href="<?php echo Mage::getUrl('customer/account'); ?>" type=""><span><?php echo $this->__("Cancel") ?></span></a>
          <button class="form-button-confirm button" type="submit"><span><?php echo $this->__("Submit") ?></span></button>
      </div>
    <?php endif; ?>
  </form>
</div>
<script async defer
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDTtEBEusRONeeNTQmL9f3LLLHHJYneHvU&callback=initMap">
</script>
<script type="text/javascript">

  var markersArray = [];

  function initMap() {
    var map = new google.maps.Map(document.getElementById('customerasaproduct-map'), {
      zoom: 9,
      center: {lat: 41.0262659, lng: 21.3280557}
    });
    var geocoder = new google.maps.Geocoder();

    document.getElementById('map-submit').addEventListener('click', function() {
      geocodeAddress(geocoder, map);
    });
  }

  function geocodeAddress(geocoder, resultsMap) {
    var address = document.getElementById('address').value;
    geocoder.geocode({'address': address}, function(results, status) {
      if (status === 'OK') {
        resultsMap.setCenter(results[0].geometry.location);
        var marker = new google.maps.Marker({
          map: resultsMap,
          position: results[0].geometry.location
        });

        $j('#map-input-lat').val(marker.getPosition().lat());
        $j('#map-input-lng').val(marker.getPosition().lng());

        markersArray.push(marker);
      } else {
        alert('Geocode was not successful for the following reason: ' + status);
      }
    });
  }

  function clearOverlays() {
    for (var i = 0; i < markersArray.length; i++ ) {
      markersArray[i].setMap(null);
    }
    markersArray.length = 0;
  }

</script>
<script type="text/javascript">
    //< ![CDATA[

        // Validate cover image
        function validateCover(){
          var inp = document.getElementById('cover-image');
          if(inp.files.length === 0){
              $j(".cover-image-validation").css('display','block');
              return false;
          }
        }

        var businessRegister = new VarienForm('business-register');

        Validation.add('validate-hours', 'Please enter a valid working hours in the following format: 08:00', function(v) {
            return Validation.get('IsEmpty').test(v) || /^([01]?[0-9]|2[0-3]):[0-5][0-9]$/i.test(v)
        });

        var saturdayFrom = "<?php echo $_product->getSaturday(); ?>";
        var saturdayTo = "<?php echo $_product->getSaturday(); ?>";
        var sundayFrom = "<?php echo $_product->getSaturday(); ?>";
        var sundayTo = "<?php echo $_product->getSaturday(); ?>";


        $j(document).ready(function() {

          $j("#saturday-radio-enable").prop("checked", true);
          if (saturdayFrom == '' && saturdayTo == '') {
            $j("#saturday-from-input").prop("disabled", true);
            $j("#saturday-to-input").prop("disabled", true);
            $j("#saturday-radio-disable").prop("checked", true);
            $j("#saturday-from-input").css('background-color','#ededed');
            $j("#saturday-to-input").css('background-color','#ededed');
          }

          $j("#saturday-radio-enable").on("click", function() {
            $j("#saturday-from-input").prop("disabled", false);
            $j("#saturday-from-input").css('background-color','white');
            $j("#saturday-to-input").prop("disabled", false);
            $j("#saturday-to-input").css('background-color','white');
          });

          $j("#saturday-radio-disable").on("click", function() {
            $j("#saturday-from-input").prop("disabled", true);
            $j("#saturday-from-input").val("");
            $j("#saturday-from-input").css('background-color','#ededed');
            $j("#saturday-to-input").prop("disabled", true);
            $j("#saturday-to-input").val("");
            $j("#saturday-to-input").css('background-color','#ededed');
          });

        });

        $j(document).ready(function() {

          $j("#sunday-radio-enable").prop("checked", true);
          if (sundayFrom == '' && sundayTo == '') {
            $j("#sunday-from-input").prop("disabled", true);
            $j("#sunday-to-input").prop("disabled", true);
            $j("#sunday-radio-disable").prop("checked", true);
            $j("#sunday-from-input").css('background-color','#ededed');
            $j("#sunday-to-input").css('background-color','#ededed');
          }

          $j("#sunday-radio-enable").on("click", function() {
            $j("#sunday-from-input").prop("disabled", false);
            $j("#sunday-from-input").css('background-color','white');
            $j("#sunday-to-input").prop("disabled", false);
            $j("#sunday-to-input").css('background-color','white');
          });

          $j("#sunday-radio-disable").on("click", function() {
            $j("#sunday-from-input").prop("disabled", true);
            $j("#sunday-from-input").val("");
            $j("#sunday-from-input").css('background-color','#ededed');
            $j("#sunday-to-input").prop("disabled", true);
            $j("#sunday-to-input").val("");
            $j("#sunday-to-input").css('background-color','#ededed');
          });

        });

        function imageValidation(){
            var fileInput = document.getElementById('cover-image');
            var filePath = fileInput.value;
            var allowedExtensions = /(\.jpg|\.jpeg|\.png|\.gif)$/i;
            if(!allowedExtensions.exec(filePath)){
                alert("<?php echo $this->__('Please upload file having extensions jpeg, jpg, png, gif only'); ?>");
                fileInput.value = '';
                return false;
            }
        }

    //]]>
</script>
