<?php
	$_order = new Mage_Sales_Model_Order();
	$orderId = Mage::getSingleton('checkout/session')->getLastRealOrderId();
	$_order->loadByIncrementId($orderId);
	$custid     = $_order->customer_id;
	$customerId = $custid;
	$customer = Mage::getModel('customer/customer')->load($customerId); 
	$customerAddress = array();
	foreach ($customer->getAddresses() as $address){$customerAddress = $address->toArray();}
	$countryModel = Mage::getModel('directory/country')->loadByCode($customerAddress['country_id']);
	$countryName  = $countryModel->getName();
	$amountToPay=$details1=$details2=$paymentOkUrl=$paymentFailUrl=$firstName==$lastName=$address=$city=$zip=$country=$telephone=$email=$originalAmount=$originalCurrency=$series=$finalChecksum=$checksum=$PayToMerchant="";
	$unique				=	time();
	$amountToPay		=	number_format((float)$_order->grand_total, 2, '.', '') * 100;
	$PayToMerchant		=   "1000000744";
	$MerchantName		=   "TV Studio 7 Doo";
	$amountCurrency		=   "MKD";
	$details1			=	"Invoice ".rand();
	$details2			=	$unique;
	$paymentOkUrl		=	"http://vebstrana.com.mk/checkout/onepage/success/";
	$paymentFailUrl		=	"http://vebstrana.com.mk.com/checkout/cart/";
	$firstName			=	$_order->customer_firstname;
	$lastName			=	$_order->customer_lastname;
	$address			=	$customerAddress['company'];
	$city				=   $customerAddress['city'];			
	$zip				=   $customerAddress['postcode'];			
	$country			=   $customerAddress['country_id'];		
	$telephone			=   $customerAddress['telephone'];			
	$email				=   $_order->customer_email;			
	$originalAmount		=   number_format((float)$_order->base_grand_total, 2, '.', '');			
	$originalCurrency	=   $_order->base_currency_code;
	$password			=   "";
	$ap					= 	str_pad(strlen($amountToPay), 3, '0', STR_PAD_LEFT);
	$pm					= 	str_pad(strlen($PayToMerchant), 3, '0', STR_PAD_LEFT);
	$mn					= 	str_pad(strlen($MerchantName), 3, '0', STR_PAD_LEFT);
	$ac					= 	str_pad(strlen($amountCurrency), 3, '0', STR_PAD_LEFT);
	$d1					= 	str_pad(strlen($details1), 3, '0', STR_PAD_LEFT);
	$d2					= 	str_pad(strlen($details2), 3, '0', STR_PAD_LEFT);
	$po					= 	str_pad(strlen($paymentOkUrl), 3, '0', STR_PAD_LEFT);
	$pf					= 	str_pad(strlen($paymentFailUrl), 3, '0', STR_PAD_LEFT);
	$fn					= 	str_pad(strlen($firstName), 3, '0', STR_PAD_LEFT);
	$ln					= 	str_pad(strlen($lastName), 3, '0', STR_PAD_LEFT);
	$ad					= 	str_pad(strlen($address), 3, '0', STR_PAD_LEFT);
	$ct					= 	str_pad(strlen($city), 3, '0', STR_PAD_LEFT);
	$zp					= 	str_pad(strlen($zip), 3, '0', STR_PAD_LEFT);
	$cn					= 	str_pad(strlen($country), 3, '0', STR_PAD_LEFT);
	$tn					= 	str_pad(strlen($telephone), 3, '0', STR_PAD_LEFT);
	$em					= 	str_pad(strlen($email), 3, '0', STR_PAD_LEFT);
	$om					= 	str_pad(strlen($originalAmount), 3, '0', STR_PAD_LEFT);
	$oc					= 	str_pad(strlen($originalCurrency), 3, '0', STR_PAD_LEFT);
	$checksumSeries		=	"18AmountToPay,PayToMerchant,MerchantName,AmountCurrency,Details1,Details2,PaymentOKURL,PaymentFailURL,FirstName,LastName,Address,City,Zip,Country,Telephone,Email,OriginalAmount,OriginalCurrency,";
	$seriesCount 		=	$ap.$pm.$mn.$ac.$d1.$d2.$po.$pf.$fn.$ln.$ad.$ct.$zp.$cn.$tn.$em.$om.$oc;
	$series 			=	$ap.$pm.$mn.$ac.$d1.$d2.$po.$pf.$fn.$ln.$ad.$ct.$zp.$cn.$tn.$em.$om.$oc.$amountToPay.$PayToMerchant.$MerchantName.$amountCurrency.$details1.$details2.$paymentOkUrl.$paymentFailUrl.$firstName.$lastName.$address.$city.$zip.$country.$telephone.$email.$originalAmount.$originalCurrency.$password;
	$finalChecksum      =   $checksumSeries.$seriesCount;
	$md5Checksum        =	$checksumSeries.$series;
	$checksum			= 	md5($md5Checksum);
?>
<form name="mygatewayform" action='https://www.cpay.com.mk/client/Page/default.aspx?xml_id=/mk-MK/.loginToPay/.payNotRegistered/.VIPRedirect' method='post'>
	<input type="hidden" name="AmountToPay" value="<?php echo $amountToPay; ?>">
	<input type="hidden" name="PayToMerchant" value="<?php echo $PayToMerchant; ?>">
	<input type="hidden" name="MerchantName" value="<?php echo $MerchantName; ?>">
	<input type="hidden" name="AmountCurrency" value="<?php echo $amountCurrency; ?>">
	<input type="hidden" name="Details1" value="<?php echo $details1; ?>">
	<input type="hidden" name="Details2" value="<?php echo $details2; ?>">
	<input type="hidden" name="PaymentOKURL" value="<?php echo $paymentOkUrl; ?>">
	<input type="hidden" name="PaymentFailURL" value="<?php echo $paymentFailUrl; ?>">
	<input type="hidden" name="FirstName" value="<?php echo $firstName; ?>">
	<input type="hidden" name="LastName" value="<?php echo $lastName; ?>">
	<input type="hidden" name="Address" value="<?php echo $address; ?>">
	<input type="hidden" name="City" value="<?php echo $city; ?>">
	<input type="hidden" name="Zip" value="<?php echo $zip; ?>">
	<input type="hidden" name="Country" value="<?php echo $country; ?>">
	<input type="hidden" name="Telephone" value="<?php echo $telephone; ?>">
	<input type="hidden" name="Email" value="<?php echo $email; ?>">
	<input type="hidden" name="OriginalAmount" value="<?php echo $originalAmount; ?>">
	<input type="hidden" name="OriginalCurrency" value="<?php echo $originalCurrency; ?>">
	<input id='CheckSumHeader' name='CheckSumHeader' value="<?php echo $finalChecksum; ?>" type='hidden' />
	<input type='hidden' name='CheckSum' value='<?php echo $checksum; ?>'/>
</form>
<script type="text/javascript">document.mygatewayform.submit();</script>