<!-- Search -->
<?php
  $category = Mage::getModel('catalog/category');
  if(is_object(Mage::registry('current_category'))){
    $current_category_path=Mage::registry('current_category')->getPathIds();
  }else{
    $current_category_path = array();
  }
  $category->load(Mage::app()->getStore()->getRootCategoryId());
  $children_string = $category->getChildren();
  $children = explode(',',$children_string);
  $extra_options='';

  foreach($children as $c){
    $selected = (in_array($c, $current_category_path))?'SELECTED':'';
    $extra_options.= '<option value="' . $c . '" ' . $selected . '>' . $category->load($c)->getName() . '</option>' . "\n";
  }
?>

<div class="home-container-poznat">
  <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('home-block-bidi-javen')->toHtml();?>
  <div class="home-container-poznat-search">
    <form id="search_mini_form" action="<?php echo $this->helper('catalogSearch')->getResultUrl() ?>" method="get">
        <fieldset>
            <div class="mini-search">
              <input id="search" type="text" class="search-input" name="<?php echo $this->helper('catalogSearch')->getQueryParamName() ?>" value="<?php echo $this->helper('catalogSearch')->getEscapedQueryText() ?>" />
              <select name="cat" id="cat" class="search-select">
                 <option value=""><?php echo $this->__('All Departments') ?></option>
                 <?php echo $extra_options ?>
              </select>
              <input type="submit" class="search-submit" value="" alt="<?php echo $this->__('Search') ?>" />
              <div id="search_autocomplete" class="search-autocomplete"></div>
              <script type="text/javascript">
                //<![CDATA[
                    var searchForm = new Varien.searchForm('search_mini_form', 'search', '<?php echo $this->__('Search') ?>');
                    searchForm.initAutocomplete('<?php echo $this->helper('catalogSearch')->getSuggestUrl() ?>', 'search_autocomplete');
                //]]>
              </script>
            </div>
        </fieldset>
    </form>
  </div>
</div>

<?php echo $this->getChildHtml(‘footerSearch’) ?>
<!-- Categories -->
<?php
    $_helper = Mage::helper('catalog/category');
    $categories = $_helper->getStoreCategories();
?>
<div class="home-container-categories">
  <ol>
    <?php foreach ($categories as $_category): ?>
      <?php
        $category = Mage::getModel('catalog/category')->load($_category->getId());
      ?>
          <li>
            <a style="background-color: <?php echo $category->getDescription() ?>" href="<?php echo $category->getURL(); ?>">
              <img src="<?php echo Mage::getBaseUrl('media').'catalog/category/' . $category->getImage() ?>" />
            </a>
            <p style="color: <?php echo $category->getDescription() ?>" ><?php echo $category->getName() ?></p>
          </li>
    <?php endforeach; ?>
  </ol>
</div>
