<!-- Packages -->
<?php
  $attrSetName = 'Packages';
  $attributeSetId = Mage::getModel('eav/entity_attribute_set')
      ->load($attrSetName, 'attribute_set_name')
      ->getAttributeSetId();

  $products = Mage::getModel('catalog/product')->getCollection();
  $products->addAttributeToFilter('attribute_set_id',$attributeSetId);

  $products->addAttributeToSelect('*');

  $products->load();
?>

<div class="home-container-packages-container">
  <h2><?php echo $this->__("Odberete paket i pretplatete se vednas") ?></h2>
  <?php foreach ($products as $prod): ?>
    <div class="home-container-packages-box" style="background-color: <?php echo $prod->getData("css_color"); ?>">
      <h3 class="package-box-name" ><?php echo $prod->getName() ?></h3>
      <p class="package-box-price" ><?php echo round($prod->getPrice(), 0) . " " . $this->__("denari"); ?></p>
      <p class="package-box-desc" ><?php echo $prod->getShortDescription(); ?></p>
      <a class="package-box-button button" style="color: <?php echo $prod->getData("css_color"); ?>" href="<?php echo Mage::getBaseUrl() . $prod->getUrlKey(); ?>"><?php echo $this->__("Pretplatete se vednash") ?></a>
    </div>
  <?php endforeach; ?>
</div>
